#!/bin/bash


# 安装库
#1. 将libzmath.so.1.0.0复制到/usr/local/lib/目录下
#2. 执行ldconfig，会自动生成对应的soname: libzmath.so.1 -> libzmath.so.1.0.0
#3. 手动创建link name: libzmath.so -> libzmath.so.1


# 编译程序
## 编辑程序的时候，需要告诉连接器你使用的动态库的位置，使用`-l`和`-L`选项。
gcc -o ztest ztest.c -lzmath
# 执行这个命令的时候，会自动链接libzmath.so


# 使用ldd查看库依赖，可以看到程序的依赖库有libzmath.so.1
#linux-vdso.so.1 =>  (0x00007ffec3375000)
#libzmath.so.1 => /usr/local/lib/libzmath.so.1 (0x00007f8adff68000)
#libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8adfba3000)
#/lib64/ld-linux-x86-64.so.2 (0x00007f8ae0194000)

exit 0
